### ISSUE TITLE
Heroku says sourse code is violating the Salesforce acceptance

### ISSUE THREAD

**Issue by ocecer** [Ayush7445/telegram-forwarder_auto#4]
Hi I face with the following error during the deploying. 

We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

Can you please help?

**Comment by IshwaranRudhara** [comment]
fork, or clone to your private repo! then DEPOY!

**Comment by Lacosta1ss** [comment]
> fork, or clone to your private repo! then DEPOY!

@IshwaranRudhara @Ayush7445  Can you explain more please? I am facing same issue.
Thanks in advance!

**Comment by Ayush7445** [comment]
Fork this repo and then change the repo link in app.json and then deploy the repo and still facing problem then privately upload this repo and then deploy, it will definitely work.

If you still didn't understood then Tutorial video will be uploaded within few days
