### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Lida1606** [Ayush7445/telegram-forwarder_auto#6]
Traceback (most recent call last):
  File "/home/pi/Desktop/Telegrambots/telegram-forwarder_auto/bot.py", line 24, in <module>
    APP_ID = config("APP_ID", default=None, cast=int)
  File "/home/pi/.local/lib/python3.9/site-packages/decouple.py", line 243, in __call__
    return self.config(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/decouple.py", line 105, in __call__
    return self.get(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/decouple.py", line 99, in get
    return cast(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by devmexican** [comment]
That is because the variables are not configured, you can replace that data with an environment variable, to protect your information or place the values to do the tests.

**Comment by devmexican** [comment]
If it is the first time, it will ask for your phone number and send a code to your telegram app.
Luck.


# Basics
APP_ID = app_id
API_HASH =api_hash

try:
    BotzHubUser = TelegramClient('name', APP_ID, API_HASH)
    BotzHubUser.start()
except Exception as ap:
    print(f"ERROR - {ap}")
    exit(1)

#id_channel From
@BotzHubUser.on(events.NewMessage(incoming=True, chats=id_channel))
async def sender_bH(event):
   
#id_channel to
await client.forward_messages(id_channel_,event.message)

print("Bot has started.")
BotzHubUser.run_until_disconnected()

**Comment by ahmedhasanhg** [comment]
its the first time and i got the phone number code already 
and the bot has started but still no messages forwarded 
and i tried 2 times and deleted the app and do it again and still the same problem

**Comment by devmexican** [comment]
If I already send you the code it means that we are doing well
Can you paste your code, so I can see the forwarding option?

**Comment by ahmedhasanhg** [comment]
im sorry i was trying to forward messages from bot to channel
is it possible ?

**Comment by devmexican** [comment]
of course it is possible
